FROM golang AS builder

WORKDIR /usr/src/app

COPY . .

RUN cd src/hello/ && go build hello.go

FROM node:16-alpine3.11

WORKDIR /usr/src/app

COPY --from=builder /usr/src/app .

CMD [ "./src/hello/hello" ]
